chorelist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^chores/', include('chores.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

chores/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^newlist/$', views.newlist, name='newlist'),
    url(r'^(?P<chorelist_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<chorelist_id>[0-9]+)/deletelist/$', views.deletelist, name='deletelist'),
    url(r'^(?P<chorelist_id>[0-9]+)/newchore/$', views.newchore, name='newchore'),
    url(r'^(?P<chorelist_id>[0-9]+)/chores/(?P<chore_id>[0-9]+)/$', views.choredetail, name='choredetail'),
    url(r'^(?P<chorelist_id>[0-9]+)/chores/(?P<chore_id>[0-9]+)/update/$', views.updatechore, name='updatechore'),
    url(r'^(?P<chorelist_id>[0-9]+)/chores/(?P<chore_id>[0-9]+)/deletechore/$', views.deletechore, name='deletechore'),

]

chores/models.py
from django.db import models

# Create your models here.

class ChoreList(models.Model):
    name = models.CharField(max_length=100)
    due_date = models.DateTimeField()

    def __str__(self):
        return self.name

class Chore(models.Model):
    chore_list = models.ForeignKey(ChoreList)
    name =  models.CharField(max_length=100)
    due_date = models.DateTimeField()
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.name

chores/views.py
from django.shortcuts import get_object_or_404, render

# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from .models import ChoreList,Chore

def index(request):
    lists = ChoreList.objects.all()
    return render(request, 'chores/index.html', {'chorelists':lists})

def newlist(request):
    if request.POST:
        list = ChoreList(name=request.POST['name'], due_date=request.POST['duedate'])
        list.save()
        return HttpResponseRedirect("/chores")
    else:
        return render(request, 'chores/newlist.html', {})
    
def newchore(request, chorelist_id):
    if request.POST:
        list = get_object_or_404(ChoreList, pk=chorelist_id)
        chore = Chore(name=request.POST['name'], due_date=request.POST['duedate'], complete=request.POST['complete'])
        chore.chore_list = list
        chore.save()
        return HttpResponseRedirect("/chores/"+chorelist_id)
    else:
        list = get_object_or_404(ChoreList, pk=chorelist_id)
        return render(request, 'chores/newchore.html', {'chorelist':list})

def deletelist(request, chorelist_id):
    list = ChoreList.objects.get(pk=chorelist_id)
    list.delete()
    return HttpResponseRedirect("/chores")
    
def deletechore(request, chorelist_id, chore_id):
    chore = Chore.objects.get(pk=chore_id)
    chore.delete()
    return HttpResponseRedirect("/chores/"+chorelist_id)
    
def detail(request, chorelist_id):
    list = get_object_or_404(ChoreList, pk=chorelist_id)
    return render(request, 'chores/detail.html', {'chorelist':list})    

def choredetail(request, chorelist_id, chore_id):
    list = get_object_or_404(ChoreList, pk = chorelist_id)
    chore = get_object_or_404(Chore, pk = chore_id)
    return render(request, 'chores/choredetail.html',{'chorelist':list, 'chore':chore})    

def updatechore(request, chorelist_id, chore_id):
    chore = get_object_or_404(Chore, pk = chore_id)
    if 'complete' in request.POST:
        chore.complete = True
    else:
        chore.complete = False
    chore.save()
    return HttpResponseRedirect('/chores/'+ chorelist_id + '/chores/' + chore_id)    

chores/templates/base.html
<html>
  <head>
    <title>My Chores App</title>
    
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav">
	<li><a class="navbar-brand" href="#">My Chores App</a></li>	
        <li><a href="/chores">Home</a></li>
    </ul>
    </div>
  </div>
  </nav>

    
   <div class="row-fluid" align=center>
     <div class="span7 offset2">
      {% block primary %}{% endblock %}
     </div> 
   </div>

  </body>
</html>

chores/templates/chores/choredetail.html
{% extends 'base.html' %}
{% block primary %}
<h1>{{chore}}</h1>
<p>Due date: {{chore.due_date}}</p>

<form action="/chores/{{chorelist.id}}/chores/{{chore.id}}/update/" method="post">
    {% csrf_token %}
    <label for="complete">Is Complete</label>
    {% if chore.complete %}  
        <input type="checkbox" name="complete" id="complete" checked><br/><br/>
    {% else %}
        <input type="checkbox" name="complete" id="complete"><br/><br/>
    {% endif %}
    <input type="submit" value="Update"/>
</form>
<a href = "/chores/{{chorelist.id}}/chores/{{chore.id}}/deletechore">Delete this chore</a>
{% endblock %}

chores/templates/chores/detail.html
{% extends 'base.html' %}
{% block primary %}
<h1>{{chorelist}}</h1>
<ul>
    {% for chore in chorelist.chore_set.all %}
        <li><a href = "/chores/{{chorelist.id}}/chores/{{chore.id}}">{{chore}}</a></li>
    {% endfor %}
</ul>
<a href = "/chores/{{chorelist.id}}/newchore">Add a new chore</a> &nbsp &nbsp
<a href = "/chores/{{chorelist.id}}/deletelist">Delete this list</a>
{% endblock %}

chores/templates/chores/index.html
{% extends 'base.html' %}
{% block primary %}

<h3> Your currently stored chorelists are: </h3>
{% if chorelists %}
    <ul>
        {% for chorelist in chorelists%}
            <li><a href = "/chores/{{chorelist.id}}/">{{chorelist.name}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No Chorelists are available</p>
{% endif %}

<a href="/chores/newlist">Create a new list</a>
{% endblock %}

chores/templates/chores/newchore.html
{% extends 'base.html' %}
{% block primary %}
<h1>New Chore</h1>
<form action="/chores/{{chorelist.id}}/newchore/" method="post">
    {% csrf_token %}
    <input id="chorelist" type="hidden" name="chorelist" value="{{ chorelist.id }}">
    <label for="name"> List Name</label>
    <input type="textbox" name="name" id="name" placeholder="Enter a name" /><br/><br/>
    <label for="duedate">Due Date</label>
    <input type="datetime-local" name="duedate" id="duedate"/><br/><br/>
    <label for="complete">Completed</label>
    <input type="checkbox" name="complete" id="complete"/><br/><br/>
    <input type="submit" value="Create"/>
{% endblock %}

chores/templates/chores/newlist.html
{% extends 'base.html' %}
{% block primary %}
<h1>New List</h1>
<form action="/chores/newlist/" method="post">
    {% csrf_token %}
    <label for="name"> List Name</label>
    <input type="textbox" name="name" id="name" placeholder="Enter a name" /><br/><br/>
    <label for="duedate">Due Date</label>
    <input type="datetime-local" name="duedate" id="duedate"/><br/><br/>
    <input type="submit" value="Create"/>
{% endblock %}